ALTER TABLE `user` ADD COLUMN `ip` VARCHAR(255) NOT NULL DEFAULT '';
ALTER TABLE `user` ADD COLUMN `user_agent` VARCHAR(255) NOT NULL DEFAULT '';
ALTER TABLE `user` ADD COLUMN `country` VARCHAR(255) NOT NULL DEFAULT '';
